name: CI FastAPI

on:
  push:
    branches: [US-DEV-02, develop]
  pull_request:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
