name: CI FastAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
